version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: shermatov
      POSTGRES_PASSWORD: superSecret
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
