server:
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/customer
    username: shermatov
    password: superSecret

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true






